"""Offline optimization oracles used to bound controller performance."""

from algorithms.oracles.perfect_foresight_milp import (
    BatteryAsset,
    BatteryModel,
    BatteryTrajectory,
    BoundedOracleResult,
    FormulationResult,
    PerfectForesightProblem,
    SemanticActionSeries,
    SemanticSchedule,
    SolveOptions,
    SolverInfo,
    solve_bounded_oracle,
    solve_conservative_schedule,
    solve_optimistic_lower_bound,
)
from algorithms.oracles.citylearn_fixed_service import (
    FixedServiceDiagnostics,
    FixedServiceProblem,
    build_fixed_service_battery_problem,
    expand_aggregated_battery_schedule,
)
from algorithms.oracles.individual_building_milp import (
    IndividualBuildingOracleResult,
    IndividualBuildingOracleSolution,
    combine_individual_building_schedules,
    solve_individual_building_oracles,
    split_individual_building_problems,
)
from algorithms.oracles.total_home_milp import (
    DeferrableCycleSpec,
    EVSessionSpec,
    ElectricalServiceSpec,
    LinearStorageSpec,
    TotalHomeProblem,
    TotalHomeSolution,
    solve_total_home_milp,
)
from algorithms.oracles.citylearn_total_home import (
    CityLearnTotalHomeBuild,
    build_citylearn_total_home_problem,
)
from algorithms.oracles.citylearn_total_energy import (
    CityLearnTotalEnergyBuild,
    CityLearnTotalEnergyDiagnostics,
    build_citylearn_total_energy_problem,
)
from algorithms.oracles.total_energy_milp import (
    DeferrableCycle,
    ElectricalService,
    EVSession,
    StorageAsset,
    TotalEnergyBoundedResult,
    TotalEnergyProblem,
    TotalEnergyResult,
    solve_bounded_total_energy_oracle,
    solve_total_energy_relaxation,
    solve_total_energy_schedule,
)
from algorithms.oracles.individual_total_energy_milp import (
    IndividualTotalEnergyBuildingSolution,
    IndividualTotalEnergyDecompositionResult,
    combine_individual_total_energy_results,
    solve_decomposed_individual_total_energy,
    split_individual_total_energy_problems,
    validate_individual_total_energy_separability,
)
from algorithms.oracles.scorecard_battery_milp import (
    ScorecardBatteryResult,
    ScorecardShapingOptions,
    ScorecardSolverInfo,
    solve_scorecard_battery_schedule,
)
from algorithms.oracles.local_dispatch_redistribution import (
    LocalDispatchRedistributionResult,
    redistribute_equivalent_battery_schedule,
)
from algorithms.oracles.coordinate_battery_optimizer import (
    CoordinateDispatchMetrics,
    CoordinateDispatchResult,
    optimize_physical_battery_schedule_coordinate_descent,
)

__all__ = [
    "BatteryAsset",
    "BatteryModel",
    "BatteryTrajectory",
    "BoundedOracleResult",
    "FormulationResult",
    "FixedServiceDiagnostics",
    "FixedServiceProblem",
    "DeferrableCycleSpec",
    "CityLearnTotalEnergyBuild",
    "CityLearnTotalEnergyDiagnostics",
    "CityLearnTotalHomeBuild",
    "EVSessionSpec",
    "ElectricalServiceSpec",
    "DeferrableCycle",
    "ElectricalService",
    "EVSession",
    "IndividualBuildingOracleResult",
    "IndividualBuildingOracleSolution",
    "IndividualTotalEnergyBuildingSolution",
    "IndividualTotalEnergyDecompositionResult",
    "LinearStorageSpec",
    "PerfectForesightProblem",
    "SemanticActionSeries",
    "SemanticSchedule",
    "ScorecardBatteryResult",
    "ScorecardShapingOptions",
    "ScorecardSolverInfo",
    "SolveOptions",
    "SolverInfo",
    "TotalHomeProblem",
    "TotalHomeSolution",
    "StorageAsset",
    "TotalEnergyBoundedResult",
    "TotalEnergyProblem",
    "TotalEnergyResult",
    "solve_bounded_oracle",
    "solve_conservative_schedule",
    "solve_optimistic_lower_bound",
    "solve_scorecard_battery_schedule",
    "LocalDispatchRedistributionResult",
    "redistribute_equivalent_battery_schedule",
    "CoordinateDispatchMetrics",
    "CoordinateDispatchResult",
    "optimize_physical_battery_schedule_coordinate_descent",
    "solve_bounded_total_energy_oracle",
    "solve_total_energy_relaxation",
    "solve_total_energy_schedule",
    "build_fixed_service_battery_problem",
    "build_citylearn_total_energy_problem",
    "build_citylearn_total_home_problem",
    "combine_individual_building_schedules",
    "combine_individual_total_energy_results",
    "expand_aggregated_battery_schedule",
    "solve_individual_building_oracles",
    "solve_decomposed_individual_total_energy",
    "split_individual_building_problems",
    "split_individual_total_energy_problems",
    "solve_total_home_milp",
    "validate_individual_total_energy_separability",
]
